version: 2

sitemaps:
  site:
    origin: https://www.aemdev.org
    lastmod: YYYY-MM-DD
    languages:
      en:
        source: /en/query-index.json
        destination: /en/sitemap.xml
        hreflang: en
        alternate: /en/{path}
      de:
        source: /de/query-index.json
        destination: /de/sitemap.xml
        hreflang: de
        alternate: /de/{path}
      fr:
        source: /fr/query-index.json
        destination: /fr/sitemap.xml
        hreflang: fr
        alternate: /fr/{path}
      es:
        source: /es/query-index.json
        destination: /es/sitemap.xml
        hreflang: es
        alternate: /es/{path}
      it:
        source: /it/query-index.json
        destination: /it/sitemap.xml
        hreflang: it
        alternate: /it/{path}
      pl:
        source: /pl/query-index.json
        destination: /pl/sitemap.xml
        hreflang: pl
        alternate: /pl/{path}
      pt:
        source: /pt/query-index.json
        destination: /pt/sitemap.xml
        hreflang: pt
        alternate: /pt/{path}
      ko:
        source: /ko/query-index.json
        destination: /ko/sitemap.xml
        hreflang: ko
        alternate: /ko/{path}
      ja:
        source: /ja/query-index.json
        destination: /ja/sitemap.xml
        hreflang: ja
        alternate: /ja/{path}
      zh-cn:
        source: /zh-cn/query-index.json
        destination: /zh-cn/sitemap.xml
        hreflang: zh-CN
        alternate: /zh-cn/{path}
      zh-tw:
        source: /zh-tw/query-index.json
        destination: /zh-tw/sitemap.xml
        hreflang: zh-TW
        alternate: /zh-tw/{path}
